### PR TITLE
added CXX standard option in cmakelist

### PR DESCRIPTION
**Pull request by samuelstjean**
Pretty much that, it currently uses c++ 98, which should be the standard. And people can easily change it to c++11/14 the same way for future use.

I can't edit the wiki, but you could add something like

## Compiling with C++11 features

In case wxwidget raises an error such as
~~~bash
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. 
This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
~~~

Simply edit the file src/CMakeLists.txt and change at the top

set(CMAKE_CXX_STANDARD 98)

to

set(CMAKE_CXX_STANDARD 11)

And regenerate the cmake cache.

### CODE REVIEW

**Comment by samuelstjean** [comment]
Also fixes #222

**Comment by jchoude** [comment]
Just to make sure, you say that in the wiki, we should add to change 

```
set(CMAKE_CXX_STANDARD 98)
```
to
```
set(CMAKE_CXX_STANDARD 11)
```
but, in your proposed changes, it is already set as 
```
set(CMAKE_CXX_STANDARD 11)
```
Is this intented?

**Comment by jchoude** [comment]
@chamberm Could you test this on your classical setup on Windows please?

**Comment by chamberm** [comment]
Well In the cmake I only see the IF linux part. 
IF(UNIX)
# Global compiler flags for LINUX:
#-----------------------
# -Wno-long-long    since on Ubuntu 8.10 it won't compile without it
# -ansi             force ISO-C++98 compliance (not GNU++98)
SET( CMAKE_CXX_FLAGS "-Wall -ansi -Wno-long-long" )
SET( CMAKE_CXX_FLAGS_DEBUG "-g -DDEBUG -O0" )
SET( CMAKE_CXX_FLAGS_RELEASE "-O3" )
SET( CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -DDEBUG -O2" )
ENDIF(UNIX)

is this what you mean sam? If yes, this doesnt affect windows builds then

**Comment by jchoude** [comment]
@chamberm Thanks, that's a  very good point. @samuelstjean Please set it only in the Linux part.

**Comment by chamberm** [comment]
Also, can this problem occur on mac ? Should this be adressed here also then We didn't build a mac solution in over 2 years

**Comment by jchoude** [comment]
@chamberm It might happen, but until someone tries it on a Mac, I prefer not touching it.

**Comment by samuelstjean** [comment]
wait, wait wait, no I made a mistake, I meant to use the flag 98 (so that it does not change anything at all) and not build in my case. I just obviously pushed the build that works by mistake. It's probably better to let the 0.0001% of people (i.e. me) with the problem fix it manually until it becomes widespread, since it would bee terrible to just break stuff inadvertently.

**Comment by jchoude** [comment]
@samuelstjean That's exactly what I suspected. Now, could you move it just in the Linux section of the CMakeLists.txt?

**Comment by jchoude** [comment]
Seems good.

Next time, please don't do a rebase if you already pushed something. It breaks all hell when I pull your changes. Just merge master...

**Comment by samuelstjean** [comment]
Yeah I know, I wanted to squash useless commits, it also took me forever to get it working again. So rebasing is a terrible idea?

**Comment by jchoude** [comment]
Rebasing is a terrible idea if you already pushed your code to a public repo where people might have fetched it. Especially if you try to rewrite the history, as you did in this case from your comment.

I don't really care about "useless" commits, except if there are like 100 of them. In the current case, your history was ok.

**Pull request merged**
